name: Scheduled API Request

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  make-request:
    runs-on: self-hosted

    steps:
      - name: Make API Request
        run: |
          curl --request GET \
          --url 'https://music.bocono-labs.com/api/article/store'
          curl --request GET \
          --url 'https://music.bocono-labs.com/api/article/parse'
