name: Scheduled API Request

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  store:
    runs-on: self-hosted
    steps:
      - name: Pull the News from the Brave Search API and Store them in the Database
        run: |
          curl --request GET \
          --url 'https://music.bocono-labs.com/api/article/store' \
          --header "Authorization: ${{ secrets.API_TOKEN }}"

  parse:
    runs-on: self-hosted
    steps:
      - name: Parse the News using Readability
        run: |
          curl --request GET \
          --url 'https://music.bocono-labs.com/api/article/parse' \
          --header "Authorization: ${{ secrets.API_TOKEN }}"
