name: Scheduled API Request

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  store:
    runs-on: self-hosted
    steps:
      - name: Pull the News from the Brave Search API and Store them in the Database
        run: |
          curl --request POST \
          --url 'https://music.bocono-labs.com/api/article/store' \
          --header "API_TOKEN: ${{ secrets.API_TOKEN }}"

  parse:
    runs-on: self-hosted
    steps:
      - name: Parse the News using Readability and Store the Parsed data in the Database
      needs: store
        run: |
          curl --request POST \
          --url 'https://music.bocono-labs.com/api/article/parse' \
          --header "API_TOKEN: ${{ secrets.API_TOKEN }}"

  embed:
    runs-on: self-hosted
    steps:
      - name: Embed the News using OpenAI and Store the Embedded data in the Database
        run: |
          curl --request POST \
          --url 'https://music.bocono-labs.com/api/article/embed' \
          --header "API_TOKEN: ${{ secrets.API_TOKEN }}"
