name: Scheduled API Request

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  make-request:
    runs-on: self-hosted

    steps:
      - name: Make API Request
        run: |
          curl --request GET \
          --url 'https://music.bocono-labs.com/api/article/store' \
          --header "Authorization: ${{ secrets.API_TOKEN }}"
          curl --request GET \
          --url 'https://music.bocono-labs.com/api/article/parse' \
          --header "Authorization: ${{ secrets.API_TOKEN }}"
